[project]
name = "mq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm-client",
]

[tool.uv.sources]
llm-client = { git = "https://github.com/xlr8harder/llm_client.git" }
